# hlpr profiles configuration

[profiles]

[development]
environment = "development"
debug = true
model = "ollama/gemma3"
optimizer = "bootstrap"
iters = 2
include_unverified = true
max_bootstrapped_demos = 4
max_labeled_demos = 8
api_base = "http://localhost:11434"

[staging]
environment = "staging"
debug = false
model = "gpt-3.5-turbo"
optimizer = "mipro"
iters = 5
include_unverified = false
max_bootstrapped_demos = 8
max_labeled_demos = 16

[production]
environment = "production"
debug = false
model = "gpt-4"
optimizer = "mipro"
iters = 10
include_unverified = false
max_bootstrapped_demos = 16
max_labeled_demos = 32